### ISSUE TITLE
implementation is unclear

### ISSUE THREAD

**Issue by WCPeragine** [JB1905/react-universal-tilt#1]
First of all, thanks for the work you've put into this project, it is greatly appreciated.

Let me preface this by saying I am a beginning coder and not very good, so the issue is likely more on my end than it is on yours. My issue is that I can't understand how I am supposed to pass options in the <ReactTilt> component. I have created my elements and gave have react tilt working, but I can not figure out how to give them reverse or disable y or any of these options because no matter how many times I read it, I can't figure out what the documentation wants me to do.

I have read this section of the readme about 100 times already and I just can't understand how to do it.

<ReactTilt
  options={ /* options */ }
  styles={ /* CSS styles */ }
  className={ /* class name(s) */ }
  tiltChange={ /* event output destination */ }
/>

I was hoping you could either 
A) make the documentation more clear here, or 
B) simply explain to me how to do it, and I will happily edit the documentation myself to make it more clear.

thanks for your time, and hard work.

**Comment by JB1905** [comment]
I will update the documentation today (I will add a section in README.md with an example implementation). react-universal-tilt uses universal-tilt.js, installed together by NPM. The Props in readme section has a link to the universal-tilt.js option.

**Thank You for information!**

**Comment by JB1905** [comment]
[Check this README.md update](https://github.com/JB1905/react-universal-tilt#examples). I added 2 examples of implementation in the examples section.

**Comment by WCPeragine** [comment]
Thank you so much! This is much clearer and I now realize exactly what I was doing wrong (I was only using 1 set of { }'s)
