### ISSUE TITLE
The destroy method is not working.

### ISSUE THREAD

**Issue by 74flame47** [JB1905/react-universal-tilt#43]
Ok, first of all I absolutely love this package! Great job developing it! I was looking for something like this for my site. Now I'm still fairly new to react development so I can be missing something obvious but there is an issue using react-router-dom links when react-universal-tilt is active. The linked pages would not load because of this error:

"TypeError: Cannot read property 'destroy' of undefined"

When I reload the page, its fine. I really like this package so any pointers of tips would be deeply appreciated! 
![error](https://user-images.githubusercontent.com/50179312/61806583-f03b5300-ae05-11e9-9ed9-62e00955c411.PNG)

**Comment by JB1905** [comment]
Hi!
I fixed the error. The update will be available today.
Thanks!

**Comment by JB1905** [comment]
v1.3.1 with bug fix is available 🙂

**Comment by 74flame47** [comment]
Hey sorry for the late reply but it works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! You are freaking amazing man! You are helping make my dream a reality!!!!!!! I hope you find money!
